routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// var_dump($_SERVER);
// dd(Route);
// die();
// die('okok');
Route::get('/', function () {
    return view('starting_page');
});

Route::get('/info', function () {
    return view('info');
});

// Route::get('test/{name}/{age}', 'HobbyController@index');
Route::resource('hobby', 'HobbyController');
Route::resource('tag', 'TagController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get("check-md", "HomeController@checkMD")->middleware("checkType");

// MultiUploader
Route::get('/uploader', function () {
    return view('multi-uploader');
});
Route::post('/upload', function () {
    if ( request()->has( 'files' ) ) {
        $num_files = 0;
        foreach (request('files') as $file) {
            $num_files += $file->storeAs('files', $file->getClientOriginalName(), 'public') === false ? 0 : 1;
        }
        return ['uploaded' => $num_files, 'status' => $num_files > 0 ? 'success' : 'none'];
    }
});

Route::resource('user', 'UserController');
Route::get('/hobby/tag/{tag_id}', 'HobbyTagController@getFilteredHobbies')->name('hobby_tag');

// Attach / Detach Tags to Hobbies
Route::get('/hobby/{hobby_id}/tag/{tag_id}/attach', 'HobbyTagController@attachTag');
Route::get('/hobby/{hobby_id}/tag/{tag_id}/detach', 'HobbyTagController@detachTag');

// Delete images of hobby
Route::get('/delete-images/hobby/{hobby_id}', 'HobbyController@deleteImages');
// Delete images of user
Route::get('/delete-images/user/{user_id}', 'UserController@deleteImages');

resources/views/bk_home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    <h2>Hello {{ auth()->user()->name }}</h2>
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

{{--                    {{ __('You are logged in!') }}--}}
                    <a href="{{ route('hobby.create') }} " class="btn btn-success btn-sm">
                        <i class="fas fa-plus-circle"></i> Create new hobby
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-md-9">
                            <h2>Hello {{ auth()->user()->name }}</h2>
                            <h5>Your Motto</h5>
                            <p>{{ auth()->user()->motto ?? '' }}</p>
                            <h5>Your "About Me" -Text.</h5>
                            <p>{{ auth()->user()->about_me ?? '' }}</p>
                            <div class="my-3">
                                <a href="/user/{{ auth()->user()->id }}/edit" class="btn btn-primary"><i class="fas fa-edit"></i> Edit Profile</a>
                            </div>
                        </div>
                        @if(file_exists(public_path() . '/img/users/' . auth()->user()->id . '_large.jpg'))
                            <div class="col-md-3">
                                <img class="img-thumbnail" src="/img/users/{{ auth()->user()->id }}_large.jpg" alt="{{ auth()->user()->name }}">
                            </div>
                        @endif
                    </div>



                    @isset($hobbies)
                    @if($hobbies->count() > 0)
                        <div class="col-12 d-flex justify-content-between align-items-center my-3">


                        <h3 class="row">Your Hobbies:</h3>
                        <a class="btn btn-success btn-sm" href="/hobby/create"><i class="fas fa-plus-circle"></i> Create new Hobby</a>
                        </div>
                    @endif
                    <ul class="list-group">
                        @foreach($hobbies as $hobby)
                            <li class="list-group-item">
                                @if(file_exists('img/hobbies/' . $hobby->id . '_thumb.jpg'))
                                    <a title="Show Details" href="/hobby/{{ $hobby->id }}">
                                        <img src="/img/hobbies/{{ $hobby->id }}_thumb.jpg" alt="Hobby Thumb">
                                    </a>&nbsp;
                                @endif

                                <a title="Show Details" href="/hobby/{{ $hobby->id }}">{{ $hobby->name }}</a>
                                @auth
                                    <a class="btn btn-sm btn-light ml-2" href="/hobby/{{ $hobby->id }}/edit"><i class="fas fa-edit"></i> Edit Hobby</a>
                                @endauth

                                @auth
                                    <form class="float-right" style="display: inline" action="/hobby/{{ $hobby->id }}" method="post">
                                        @csrf
                                        @method("DELETE")
                                        <input class="btn btn-sm btn-outline-danger" type="submit" value="Delete">
                                    </form>
                                @endauth
                                <span class="float-right mx-2">{{ $hobby->created_at->diffForHumans() }}</span>
                                <br>
                                @foreach($hobby->tags as $tag)
                                    <a href="/hobby/tag/{{ $tag->id }}"><span class="badge badge-{{ $tag->style }}">{{ $tag->name }}</span></a>
                                @endforeach
                            </li>
                        @endforeach
                    </ul>
                        <div class="py-3 d-flex justify-content-center">
                            {{ $hobbies->links() }}
                        </div>
                    @endisset

                    <div class="py-3 d-none">

                        <a class="btn btn-success btn-sm" href="/hobby/create"><i class="fas fa-plus-circle"></i> Create new Hobby</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/info.blade.php
@extends('layouts.app')

@section('page_title', 'About this project')
@section('page_description')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">INFO</div>

                <div class="card-body">
                    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex corrupti deleniti nisi, animi tempora distinctio voluptatum voluptatem omnis. Corrupti, ipsam! Labore sunt iste, debitis repellat quas ipsam. Quaerat, doloremque. Quia a nobis, eveniet molestias odit commodi magni cupiditate ad neque. Dolorem impedit illum iste deserunt? Eius velit perferendis dolorum ut. Nostrum soluta quisquam perspiciatis aliquam. Dolore nemo eligendi provident voluptatem odit, ab, aliquam commodi, officia at omnis veniam. Iusto minus, corporis inventore architecto illum optio voluptate iste hic doloribus nesciunt explicabo fuga facere debitis molestiae id maxime quae commodi ad deserunt quam. Fugit aut ducimus adipisci labore ad esse quo.
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/multi-uploader.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Multi Uploader Vuejs Laravel</div>

                    <multi-uploader></multi-uploader>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/starting_page.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">STARTING PAGE</div>

                <div class="card-body">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tempora ad quisquam amet nobis enim, corrupti dolore error libero neque saepe maxime quo voluptatibus accusantium ipsa! Illo, dolorum! Obcaecati nam pariatur error ex! Rerum iusto temporibus quaerat aperiam molestiae excepturi, voluptates aut dignissimos tenetur quo labore nostrum quibusdam, veniam illo dolor praesentium corrupti ex quod maxime reprehenderit iure minus. Iure maxime adipisci quibusdam enim, veritatis ipsam! Voluptatem perferendis, voluptates error illo non voluptas accusamus, dolore quaerat eos esse dicta corrupti modi natus tenetur officia possimus animi harum minus! Distinctio laborum explicabo suscipit vitae quos. Praesentium, distinctio. Fugiat nam illum, maxime, cumque facilis recusandae repellat consectetur corrupti aspernatur expedita itaque iure perspiciatis maiores at aperiam temporibus magni sapiente officiis. Quo, voluptatum.
                </div>
            </div>
        </div>
    </div>
</div>
@endsection