routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// var_dump($_SERVER);
// dd(Route);
// die();
// die('okok');
Route::get('/', function () {
    return view('starting_page');
});

Route::get('/info', function () {
    return view('info');
});

// Route::get('test/{name}/{age}', 'HobbyController@index');
Route::resource('hobby', 'HobbyController');
Route::resource('tag', 'TagController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get("check-md", "HomeController@checkMD")->middleware("checkType");

// MultiUploader
Route::get('/uploader', function () {
    return view('multi-uploader');
});
Route::post('/upload', function () {
    if ( request()->has( 'files' ) ) {
        $num_files = 0;
        foreach (request('files') as $file) {
            $num_files += $file->storeAs('files', $file->getClientOriginalName(), 'public') === false ? 0 : 1;
        }
        return ['uploaded' => $num_files, 'status' => $num_files > 0 ? 'success' : 'none'];
    }
});

Route::resource('user', 'UserController');
Route::get('/hobby/tag/{tag_id}', 'HobbyTagController@getFilteredHobbies')->name('hobby_tag');

// Attach / Detach Tags to Hobbies
Route::get('/hobby/{hobby_id}/tag/{tag_id}/attach', 'HobbyTagController@attachTag');
Route::get('/hobby/{hobby_id}/tag/{tag_id}/detach', 'HobbyTagController@detachTag');

// Delete images of hobby
Route::get('/delete-images/hobby/{hobby_id}', 'HobbyController@deleteImages');
// Delete images of user
Route::get('/delete-images/user/{user_id}', 'UserController@deleteImages');

app/Hobby.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Hobby extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'user_id',
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }
}

app/Http/Controllers/HobbyController.php
<?php

namespace App\Http\Controllers;

use App\Hobby;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Carbon;
use Intervention\Image\Facades\Image;

class HobbyController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        // $hobbies = Hobby::all();
        // $hobbies = Hobby::paginate(10);
        $hobbies = Hobby::orderBy('created_at', 'DESC')->paginate(10);


        // return $hobbies;
        // dd($hobbies);
        // dd($hobbies->toArray()[0]);
        // return view('hobby.index', compact('hobbies'));
        // return view('hobby.index')->with([
        //     'hobbies' => $hobbies,
        // ]);
        return view('hobby.index', [
            'hobbies' => $hobbies,

        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function create()
    {
        //
        return view('hobby.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|min:3',
            'description' => 'required|min:5',
            'image' => 'mimes:jpeg,bmp,png,gif,jpg',
        ]);


        $hobby = new Hobby([
            'name' => $request->name,
            'description' => $request->description,
            'user_id' => auth()->id(),
        ]);
        $hobby->save();

        if($request->image) {
            $this->saveImages($request->image, $hobby->id);
        }

        $request->session()->flash('message_success','The hobby <b>' . $hobby->name . '</b> was created.');
        return $this->index();
    }
    // public function store(Hobby $hobby) {
    //     dd(request());
    //     dd($hobby);
    //     $hobby->save();
    //     return $this->index();
    // }

    /**
     * Display the specified resource.
     *
     * @param  \App\Hobby  $hobby
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function show(Hobby $hobby)
    {
        $allTags = Tag::all();
        $usedTags = $hobby->tags;
        $availableTags = $allTags->diff($usedTags);
        return view('hobby.show')->with([
            'hobby' => $hobby,
            'usedTags' => $usedTags,
            'availableTags' => $availableTags,
//            'message_success' => Session::get('message_success'),
//            'message_warning' => Session::get('message_warning'),
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Hobby  $hobby
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(Hobby $hobby)
    {
        // dd($hobby);
        return view('hobby.edit')->with([
            'hobby' => $hobby,
//            'message_success' => Session::get('message_success'),
//            'message_warning' => Session::get('message_warning'),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Hobby  $hobby
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Hobby $hobby)
    {
        $request->validate([
            'name' => 'required|min:3',
            'description' => 'required|min:5',
            'image' => 'mimes:jpeg,bmp,png,gif,jpg',
        ]);

        if($request->image) {
            $this->saveImages($request->image, $hobby->id);
        }

        $hobby->update([
            'name' => $request['name'],
            'description' => $request['description'],
        ]);
        $request->session()->flash('message_success', 'The hobby <b>' . $hobby->name . '</b> was updated.');
        return $this->index();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Hobby $hobby
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Hobby $hobby)
    {
        $oldName = $hobby->name;
        $hobby->delete();
        request()->session()->flash('message_success', 'The hobby <b>' . $oldName . '</b> was deleted.');
        return $this->index();
    }

    public function saveImages($image_input, $hobby_id)
    {
        $image = Image::make($image_input);
        if( $image->width() > $image->height() ) {
            // landscape
            $image->widen(1200)
                ->save(public_path() . '/img/hobbies/' . $hobby_id . '_large.jpg')
                ->widen(60)
                ->save(public_path() . '/img/hobbies/' . $hobby_id . '_thumb.jpg')
                ->widen(400)->pixelate(12)
                ->save(public_path() . '/img/hobbies/' . $hobby_id . '_pixelated.jpg');


        } else {
            // portrait
            $image->heighten(900)
                ->save(public_path() . '/img/hobbies/' . $hobby_id . '_large.jpg')
                ->heighten(60)
                ->save(public_path() . '/img/hobbies/' . $hobby_id . '_thumb.jpg')
                ->heighten(400)->pixelate(12)
                ->save(public_path() . '/img/hobbies/' . $hobby_id . '_pixelated.jpg');

        }
    }

    public function deleteImages($hobby_id)
    {
        $types = ['large', 'thumb', 'pixelated'];
        foreach($types as $type) {

            if(file_exists(public_path() . '/img/hobbies/' . $hobby_id . '_' . $type .'.jpg') ) {
                unlink(public_path() . '/img/hobbies/' . $hobby_id . '_' . $type . '.jpg');
            }
        }
        request()->session()->flash('message_success','The image was deleted');
        return back();
    }
}

resources/views/hobby/bk_index.blade.php
@extends('layouts.app')

@section('page_title', 'Hobby List')
@section('page_description', '')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="card">
                @isset($filter)
                    <div class="card-header">Filtered Hobbies by <span style="font-size: 130%;" class="mx-2 badge badge-{{ $filter->style }}">{{ $filter->name }}</span>
                        <span class="float-right"><a href="/hobby">Show all hobbies</a></span>
                    </div>
                @else
                    <div class="card-header">All the Hobbies</div>
                @endisset


                <div class="card-body">
                    {{-- @dump($hobbies->toArray()) --}}
                    <ul class="list-group">
                        @foreach($hobbies as $hobby)
                            <li class="list-group-item">
                                <a href="{{ route('hobby.show', ['hobby' => $hobby]) }}" title="show details">{{ $hobby->name }}</a>
                                @auth
                                    <a href="{{ route('hobby.edit', ['hobby' => $hobby]) }}" class="btn btn-sm btn-light ml-3"><i class="fas fa-edit"></i> Edit Hobby</a>
                                @endauth
                                <span class="mx-2">Posted by:
                                    <a href="{{ route('user.show', ['user' => $hobby->user]) }}">
                                        {{ $hobby->user->name }}
                                    </a>
                                    ({{ $hobby->user->hobbies->count() }} hobbies)
                                </span>
                                @auth
                                    <form class="form-inline float-right" action="{{ route('hobby.destroy', compact('hobby')) }}" method="post">
                                        @csrf @method('DELETE')
                                        <input class="btn btn-sm btn-outline-danger" type="submit" value="Delete">
                                    </form>
                                @endauth
                                <span class="float-right mx-2">{{ $hobby->created_at->diffForHumans() }}</span>
                                <br>
                                @foreach($hobby->tags as $tag)
                                    <a href="{{ route('hobby_tag', ['tag_id' => $tag->id ]) }}"><span class="badge badge-{{ $tag->style }}">{{ $tag->name }}</span></a>
                                @endforeach
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>

            <div class="mt-3">
                {{ $hobbies->links() }}
            </div>
            @auth
                <div class="mt-2">
                    <a href="{{ route('hobby.create') }}" class="btn btn-success">
                        <i class="fas fa-plus-circle"></i>
                        Create new hobby
                    </a>
                </div>
            @endauth
        </div>
    </div>
</div>
@endsection

resources/views/hobby/bk_show.blade.php
@extends('layouts.app')

@section('page_title', 'Hobby Detail')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="card">
                <div class="card-header">Hobby Detail</div>

                <div class="card-body">
                    <h4>{{ $hobby-> name }}</h4>
					<p>{{ $hobby->description }}</p>
                    @if($hobby->tags->count() > 0)
                    <b>Used Tags:</b> (Click to remove)
                    <p>
                        @foreach($hobby->tags as $tag)
                            <a href="/hobby/{{ $hobby->id }}/tag/{{ $tag->id }}/detach"><span class="badge badge-{{ $tag->style }}">{{ $tag->name }}</span></a>
                        @endforeach
                    </p>
                    @endif
                    @if($availableTags->count() > 0)
                    <b>Available Tags:</b> (Click to assign)
                    <p>
                        @foreach($availableTags as $tag)
                            <a href="/hobby/{{ $hobby->id }}/tag/{{ $tag->id }}/attach"><span class="badge badge-{{ $tag->style }}">{{ $tag->name }}</span></a>
                        @endforeach
                    </p>
                    @endif

                </div>
            </div>
            <div class="mt-2">
                {{-- <a href="{{ route('hobby.index') }}" class="btn btn-primary"> --}}
                {{--
                <a href="{{ URL::previous() }}" class="btn btn-primary">
                    <i class="fas fa-arrow-circle-up"></i>
                    Back to overview
                </a>
                --}}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/hobby/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Create New Hobby</div>
                    <div class="card-body">
                        <form autocomplete="off" action="{{ route('hobby.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control{{ $errors->has('name') ? ' border-danger': ''}}" id="name" name="name" value="{{ old('name') }}">
                                <small class="form-text text-danger">{!! $errors->first('name') !!}</small>
                            </div>
                            <div class="form-group">
                                <label for="image">Image</label>
                                <input type="file" class="form-control{{ $errors->has('image') ? ' border-danger': ''}}" id="image" name="image" value="">
                                <small class="form-text text-danger">{!! $errors->first('image') !!}</small>
                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control{{ $errors->has('description') ? ' border-danger': ''}}" id="description" name="description" rows="5">{{ old('description') }}</textarea>
                                <small class="form-text text-danger">{!! $errors->first('description') !!}</small>
                            </div>
                            <input class="btn btn-primary mt-4" type="submit" value="Save Hobby">
                        </form>
                        <a class="btn btn-primary float-right" href="{{ route('hobby.index') }}"><i class="fas fa-arrow-circle-up"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/hobby/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Edit Hobby</div>
                    <div class="card-body">
						<form action="{{ route('hobby.update', compact('hobby')) }}" method="post" enctype="multipart/form-data" autocomplete="off">
							@csrf @method('PUT')
                            <div class="form-group">
                                <label for="name">Name</label>
								<input type="text" class="form-control{{ $errors->has('name') ? ' border-danger': ''}}" id="name" name="name" value="{{  old('name', $hobby->name) }}">
								<small class="form-text text-danger">{!! $errors->first('name') !!}</small>
                            </div>
                            @if( file_exists('img/hobbies/' . $hobby->id . '_large.jpg') )
                                <div class="mb-2 d-flex justify-content-between align-items-start">
                                    <img style="max-width: 400px; max-height:300px" src="/img/hobbies/{{ $hobby->id }}_large.jpg" alt="">
                                    <a href="/delete-images/hobby/{{$hobby->id}}" class="mx-3 btn btn-outline-danger">Delete Image</a>
                                </div>
                            @endif
                            <div class="form-group">
                                <label for="image">Image</label>
                                <input type="file" class="form-control{{ $errors->has('image') ? ' border-danger': ''}}" id="image" name="image" value="">
                                <small class="form-text text-danger">{!! $errors->first('image') !!}</small>
                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
								<textarea class="form-control{{ $errors->has('description') ? ' border-danger': ''}}" id="description" name="description" rows="5">{{ old('description', $hobby->description) }}</textarea>
								<small class="form-text text-danger">{!! $errors->first('description') !!}</small>
                            </div>
                            <input class="btn btn-primary mt-4" type="submit" value="Update Hobby">
                        </form>
                        <a class="btn btn-primary float-right" href="{{ route('hobby.index') }}"><i class="fas fa-arrow-circle-up"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/hobby/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-11">
                <div class="card">

                    @isset($filter)
                        <div class="card-header">Filtered hobbies by
                            <span style="font-size: 130%;" class="badge badge-{{ $filter->style }}">{{ $filter->name }}</span>
                            <span class="float-right"><a href="/hobby">Show all Hobbies</a></span>
                        </div>
                    @else
                        <div class="card-header">All the hobbies.</div>
                    @endisset

                    <div class="card-body">
                        <ul class="list-group">
                            @foreach($hobbies as $hobby)
                                <li class="list-group-item">
                                    @if(file_exists('img/hobbies/' . $hobby->id . '_thumb.jpg'))
                                    <a title="Show Details" href="/hobby/{{ $hobby->id }}">
                                        <img src="/img/hobbies/{{ $hobby->id }}_thumb.jpg" alt="Hobby Thumb">
                                    </a>&nbsp;
                                    @endif
                                    <a title="Show Details" href="/hobby/{{ $hobby->id }}">{{ $hobby->name }}</a>
                                    @auth
                                    <a class="btn btn-sm btn-light ml-2" href="/hobby/{{ $hobby->id }}/edit"><i class="fas fa-edit"></i> Edit Hobby</a>
                                    @endauth
                                    <span class="mx-2">Posted by: <a href="/user/{{ $hobby->user->id }}">{{ $hobby->user->name }}</a> ({{ $hobby->user->hobbies->count() }} Hobbies)
                                    @if(file_exists(public_path(). '/img/users/' . $hobby->user->id . '_thumb.jpg'))
                                        <a href="/user/{{ $hobby->user->id }}"><img class="rounded" src="/img/users/{{$hobby->user->id}}_thumb.jpg"></a>

                                    @endif
                                    </span>
                                    @auth
                                    <form class="float-right" style="display: inline" action="/hobby/{{ $hobby->id }}" method="post">
                                        @csrf
                                        @method("DELETE")
                                        <input class="btn btn-sm btn-outline-danger" type="submit" value="Delete">
                                    </form>
                                    @endauth
                                    <span class="float-right mx-2">{{ $hobby->created_at->diffForHumans() }}</span>
                                    <br>
                                    @foreach($hobby->tags as $tag)
                                        <a href="/hobby/tag/{{ $tag->id }}"><span class="badge badge-{{ $tag->style }}">{{ $tag->name }}</span></a>
                                    @endforeach
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>

                <div class="mt-3">
                    {{ $hobbies->links() }}
                </div>
                @auth
                <div class="mt-2">
                    <a class="btn btn-success btn-sm" href="/hobby/create"><i class="fas fa-plus-circle"></i> Create new Hobby</a>
                </div>
                @endauth
            </div>
        </div>
    </div>
@endsection

resources/views/hobby/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-11">
                <div class="card">
                    <div class="card-header">Hobby Detail.</div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-9">
                                <b>{{$hobby->name}}</b>
                                <p>{{$hobby->description}}</p>
                                @if($hobby->tags->count() > 0)
                                    <b>Used Tags:</b> (Click to remove)
                                    <p>
                                        @foreach($hobby->tags as $tag)
                                            <a href="/hobby/{{$hobby->id}}/tag/{{$tag->id}}/detach"><span class="badge badge-{{ $tag->style }}">{{ $tag->name }}</span></a>
                                        @endforeach
                                    </p>
                                @endif

                                @if($availableTags->count() > 0)
                                    <b>Available Tags:</b> (Click to assign)
                                    <p>
                                        @foreach($availableTags as $tag)
                                            <a href="/hobby/{{$hobby->id}}/tag/{{$tag->id}}/attach"><span class="badge badge-{{ $tag->style }}">{{ $tag->name }}</span></a>
                                        @endforeach
                                    </p>
                                @endif
                            </div>
                            <div class="col-md-3">
                                @if( Auth::user() && file_exists('img/hobbies/' . $hobby->id . '_large.jpg'))
                                    <a href="/img/hobbies/{{ $hobby->id }}_large.jpg" data-lightbox="/img/hobbies/{{ $hobby->id }}_large.jpg" data-title="{{ $hobby->name }}">
                                        <img class="img-fluid" src="/img/hobbies/{{ $hobby->id }}_large.jpg" alt="">
                                    </a>
                                    <i class="fa fa-search-plus"></i> Click image to enlarge
                                @endif
                                @if( !Auth::user() && file_exists('img/hobbies/' . $hobby->id . '_pixelated.jpg'))
                                    <img class="img-fluid" src="/img/hobbies/{{ $hobby->id }}_pixelated.jpg" alt="">
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
                <!--
                <div class="mt-2">
                    <a class="btn btn-primary btn-sm" href="{{ URL::previous() }}"><i class="fas fa-arrow-circle-up"></i> Back to Overview</a>
                </div>
                -->
            </div>
        </div>
    </div>
@endsection