routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// var_dump($_SERVER);
// dd(Route);
// die();
// die('okok');
Route::get('/', function () {
    return view('starting_page');
});

Route::get('/info', function () {
    return view('info');
});

// Route::get('test/{name}/{age}', 'HobbyController@index');
Route::resource('hobby', 'HobbyController');
Route::resource('tag', 'TagController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get("check-md", "HomeController@checkMD")->middleware("checkType");

// MultiUploader
Route::get('/uploader', function () {
    return view('multi-uploader');
});
Route::post('/upload', function () {
    if ( request()->has( 'files' ) ) {
        $num_files = 0;
        foreach (request('files') as $file) {
            $num_files += $file->storeAs('files', $file->getClientOriginalName(), 'public') === false ? 0 : 1;
        }
        return ['uploaded' => $num_files, 'status' => $num_files > 0 ? 'success' : 'none'];
    }
});

Route::resource('user', 'UserController');
Route::get('/hobby/tag/{tag_id}', 'HobbyTagController@getFilteredHobbies')->name('hobby_tag');

// Attach / Detach Tags to Hobbies
Route::get('/hobby/{hobby_id}/tag/{tag_id}/attach', 'HobbyTagController@attachTag');
Route::get('/hobby/{hobby_id}/tag/{tag_id}/detach', 'HobbyTagController@detachTag');

// Delete images of hobby
Route::get('/delete-images/hobby/{hobby_id}', 'HobbyController@deleteImages');
// Delete images of user
Route::get('/delete-images/user/{user_id}', 'UserController@deleteImages');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'motto', 'about_me',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function hobbies()
    {
        return $this->hasMany('App\Hobby');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Session;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function show(User $user)
    {
        $hobbies = $user->hobbies()->latest()->paginate(10);
        return view('user.show')->with(compact('user','hobbies'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(User $user)
    {
//        dd($user);
        return view('user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => 'required|min:3',
            'email' => 'required|email|min:5',
            'motto' => 'required|min:5',
            'about_me' => 'min:5',
            'image' => 'mimes:jpeg,bmp,png,gif,jpg',
        ]);

        if($request->image) {
            $this->saveImages($request->image, $user->id);
        }

        $user->update([
            'name' => $request['name'],
            'email' => $request['email'],
            'motto' => $request['motto'],
            'about_me' => $request['about_me'],
        ]);
        $request->session()->flash('message_success', 'The user <b>' . $user->name . '</b> was updated.');
        return redirect(route('user.show', ['user' => $user->id ]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }

    public function saveImages($image_input, $user_id)
    {
        $image = Image::make($image_input);
        if( $image->width() > $image->height() ) {
            // landscape
            $image->widen(500)
                ->save(public_path() . '/img/users/' . $user_id . '_large.jpg')
                ->widen(60)
                ->save(public_path() . '/img/users/' . $user_id . '_thumb.jpg')
                ->widen(300)->pixelate(8)
                ->save(public_path() . '/img/users/' . $user_id . '_pixelated.jpg');


        } else {
            // portrait
            $image->heighten(500)
                ->save(public_path() . '/img/users/' . $user_id . '_large.jpg')
                ->heighten(60)
                ->save(public_path() . '/img/users/' . $user_id . '_thumb.jpg')
                ->heighten(300)->pixelate(8)
                ->save(public_path() . '/img/users/' . $user_id . '_pixelated.jpg');

        }
    }

    public function deleteImages($user_id)
    {
        $types = ['large', 'thumb', 'pixelated'];
        foreach($types as $type) {

            if(file_exists(public_path() . '/img/users/' . $user_id . '_' . $type .'.jpg') ) {
                unlink(public_path() . '/img/users/' . $user_id . '_' . $type . '.jpg');
            }
        }
        request()->session()->flash('message_success','The image was deleted');
        return back();
    }
}

resources/views/user/bk_show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-11">
                <div class="card">
                    <div style="font-size: 150%;" class="card-header">{{ $user->name }}</div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-9">
                                <b>My Motto:<br>{{$user->motto}}</b>
                                <p class="mt-2"><b>About me:</b><br>{{$user->about_me}}</p>

                                <h5>Hobbies of {{ $user->name }}</h5>
                                @if($user->hobbies->count() > 0)
                                    <ul class="list-group">
                                        @foreach($user->hobbies as $hobby)
                                            <li class="list-group-item">
                                                @if(file_exists('img/hobbies/' . $hobby->id . '_thumb.jpg'))
                                                    <a title="Show Details" href="/hobby/{{ $hobby->id }}">
                                                        <img src="/img/hobbies/{{ $hobby->id }}_thumb.jpg" alt="Hobby Thumb">
                                                    </a>
                                                @endif
                                                &nbsp;<a title="Show Details" href="/hobby/{{ $hobby->id }}">{{ $hobby->name }}</a>
                                                <span class="float-right mx-2">{{ $hobby->created_at->diffForHumans() }}</span>
                                                <br>
                                                @foreach($hobby->tags as $tag)
                                                    <a href="/hobby/tag/{{ $tag->id }}"><span class="badge badge-{{ $tag->style }}">{{ $tag->name }}</span></a>
                                                @endforeach
                                            </li>
                                        @endforeach
                                    </ul>
                                @else
                                    <p>
                                        {{ $user->name }} has not created any hobbies yet.
                                    </p>
                                @endif
                            </div>
                            <div class="col-md-3">
                                @if(Auth::user() && file_exists('img/users/' . $user->id . '_large.jpg'))
                                    <img class="img-thumbnail" src="/img/users/{{$user->id}}_large.jpg" alt="{{ $user->name }}">
                                @endif
                                @if(!Auth::user() && file_exists('img/users/' . $user->id . '_pixelated.jpg'))
                                    <img class="img-thumbnail" src="/img/users/{{$user->id}}_pixelated.jpg" alt="{{ $user->name }}">
                                @endif
                            </div>
                        </div>


                    </div>

                </div>

                <div class="mt-4">
                    <a class="btn btn-primary btn-sm" href="{{ URL::previous() }}"><i class="fas fa-arrow-circle-up"></i> Back to Overview</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Edit User</div>
                    <div class="card-body">
						<form action="/user/{{$user->id}}" method="post" enctype="multipart/form-data" autocomplete="off">
							@csrf @method('PUT')
                            <div class="form-group">
                                <label for="name">Name</label>
								<input type="text" class="form-control{{ $errors->has('name') ? ' border-danger': ''}}" id="name" name="name" value="{{  old('name', $user->name) }}">
								<small class="form-text text-danger">{!! $errors->first('name') !!}</small>
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
								<input type="text" class="form-control{{ $errors->has('email') ? ' border-danger': ''}}" id="email" name="email" value="{{  old('name', $user->email) }}">
								<small class="form-text text-danger">{!! $errors->first('email') !!}</small>
                            </div>
                            <div class="form-group">
                                <label for="motto">Motto</label>
								<input type="text" class="form-control{{ $errors->has('motto') ? ' border-danger': ''}}" id="motto" name="motto" value="{{  old('name', $user->motto) }}">
								<small class="form-text text-danger">{!! $errors->first('motto') !!}</small>
                            </div>
                            @if( file_exists(public_path() . '/img/users/' . $user->id . '_large.jpg') )
                                <div class="mb-2 d-flex justify-content-between align-items-start">
                                    <img style="max-width: 400px; max-height:300px" src="/img/users/{{ $user->id }}_large.jpg" alt="">
                                    <a href="/delete-images/user/{{$user->id}}" class="mx-3 btn btn-outline-danger">Delete Image</a>
                                </div>
                            @endif
                            <div class="form-group">
                                <label for="image">Image</label>
                                <input type="file" class="form-control{{ $errors->has('image') ? ' border-danger': ''}}" id="image" name="image" value="">
                                <small class="form-text text-danger">{!! $errors->first('image') !!}</small>
                            </div>
                            <div class="form-group">
                                <label for="about_me">About Me</label>
								<textarea class="form-control{{ $errors->has('about_me') ? ' border-danger': ''}}" id="about_me" name="about_me" rows="5">{{ old('about_me', $user->about_me) }}</textarea>
								<small class="form-text text-danger">{!! $errors->first('about_me') !!}</small>
                            </div>
                            <input class="btn btn-primary mt-4" type="submit" value="Update User">
                        </form>
                        <a class="btn btn-primary float-right" href="{{ route('user.index') }}"><i class="fas fa-arrow-circle-up"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-11">
                <div class="card">
                    <div style="font-size: 150%;" class="card-header">{{ $user->name }}</div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-9">
                                <b>My Motto:<br>{{$user->motto}}</b>
                                <p class="mt-2"><b>About me:</b><br>{{$user->about_me}}</p>
                                @auth
                                <div class="text-right">
                                    <a href="/user/{{$user->id}}/edit" class="btn btn-outline-danger">Edit User</a>
                                </div>
                                @endauth
                                <h5>Hobbies of {{ $user->name }}.</h5>
                                <ul class="list-group">
                                    @if($hobbies->count() > 0)
                                        @foreach($hobbies as $hobby)
                                            <li class="list-group-item">
                                                @if(file_exists('img/hobbies/' . $hobby->id . '_thumb.jpg'))
                                                    <a title="Show Details" href="/hobby/{{ $hobby->id }}">
                                                        <img src="/img/hobbies/{{ $hobby->id }}_thumb.jpg" alt="Hobby Thumb">
                                                    </a>&nbsp;
                                                @endif
                                                <a title="Show Details" href="/hobby/{{ $hobby->id }}">{{ $hobby->name }}</a>
                                                <span class="float-right mx-2">{{ $hobby->created_at->diffForHumans() }}</span>
                                                <br>
                                                @foreach($hobby->tags as $tag)
                                                    <a href="/hobby/tag/{{ $tag->id }}"><span class="badge badge-{{ $tag->style }}">{{ $tag->name }}</span></a>
                                                @endforeach
                                            </li>
                                        @endforeach
                                </ul>
                                <div class="my-3 d-flex justify-content-center">
                                    {{ $hobbies->links() }}
                                </div>
                                @else
                                    <p>
                                        {{ $user->name }} has not created any hobbies yet.
                                    </p>
                                @endif
                            </div>
                            <div class="col-md-3">
                                @if(Auth::user() && file_exists(public_path() . '/img/users/' . $user->id . '_large.jpg'))
                                    <img class="img-thumbnail" src="/img/users/{{$user->id}}_large.jpg" alt="{{ $user->name }}">
                                @endif
                                @if(!Auth::user() && file_exists(public_path() . '/img/users/' . $user->id . '_pixelated.jpg'))
                                    <img class="img-thumbnail" src="/img/users/{{$user->id}}_pixelated.jpg" alt="{{ $user->name }}">
                                @endif
                            </div>
                        </div>


                    </div>

                </div>

                <div class="mt-4">
                    <a class="btn btn-primary btn-sm" href="{{ URL::previous() }}"><i class="fas fa-arrow-circle-up"></i> Back to Overview</a>
                </div>
            </div>
        </div>
    </div>
@endsection