routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// var_dump($_SERVER);
// dd(Route);
// die();
// die('okok');
Route::get('/', function () {
    return view('starting_page');
});

Route::get('/info', function () {
    return view('info');
});

// Route::get('test/{name}/{age}', 'HobbyController@index');
Route::resource('hobby', 'HobbyController');
Route::resource('tag', 'TagController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get("check-md", "HomeController@checkMD")->middleware("checkType");

// MultiUploader
Route::get('/uploader', function () {
    return view('multi-uploader');
});
Route::post('/upload', function () {
    if ( request()->has( 'files' ) ) {
        $num_files = 0;
        foreach (request('files') as $file) {
            $num_files += $file->storeAs('files', $file->getClientOriginalName(), 'public') === false ? 0 : 1;
        }
        return ['uploaded' => $num_files, 'status' => $num_files > 0 ? 'success' : 'none'];
    }
});

Route::resource('user', 'UserController');
Route::get('/hobby/tag/{tag_id}', 'HobbyTagController@getFilteredHobbies')->name('hobby_tag');

// Attach / Detach Tags to Hobbies
Route::get('/hobby/{hobby_id}/tag/{tag_id}/attach', 'HobbyTagController@attachTag');
Route::get('/hobby/{hobby_id}/tag/{tag_id}/detach', 'HobbyTagController@detachTag');

// Delete images of hobby
Route::get('/delete-images/hobby/{hobby_id}', 'HobbyController@deleteImages');
// Delete images of user
Route::get('/delete-images/user/{user_id}', 'UserController@deleteImages');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'style',
    ];

    public function hobbies()
    {
        return $this->belongsToMany('App\Hobby');
    }

    public function filteredHobbies()
    {
        return $this->belongsToMany('App\Hobby')
            ->wherePivot('tag_id', $this->id)
            ->orderBy('updated_at', 'DESC');
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        $tags = Tag::all();
        return view('tag.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function create()
    {
        $tag = new Tag;
        return view('tag.create', compact('tag'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response|\Illuminate\View\View
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|min:3',
            'style' => 'required|min:3',
        ]);
        $tag = new Tag([
            'name' => $request->name,
            'style' => $request->style,
        ]);
        $tag->save();
        $request->session()->flash('message_success', 'The tag <b>' . $tag->name . '</b> was created.');
        return $this->index();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(Tag $tag)
    {
        return view('tag.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\View\View
     */
    public function update(Request $request, Tag $tag)
    {
        $request->validate([
            'name' => 'required|min:3',
            'style' => 'required|min:3',
        ]);
        $tag->update([
            'name' => $request['name'],
            'style' => $request['style'],
        ]);
        $request->session()->flash('message_success','The tag <b>' . $tag->name . '</b> was updated.');
        return $this->index();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $oldName = $tag->name;
        $tag->delete();
        request()->session()->flash('message_success','The tag <b>' . $oldName . '</b> was deleted.');
        return $this->index();
    }
}

resources/views/tag/_form.blade.php
@csrf
<div class="form-group">
	<label for="name">Name</label>
	<input type="text" class="form-control{{ $errors->has('name') ? ' border-danger': ''}}" id="name" name="name" value="{{ old('name', $tag->name) }}">
	<small class="form-text text-danger">{!! $errors->first('name') !!}</small>
</div>
<div class="form-group">
	<label for="style">Style</label>
	<input type="text" class="form-control{{ $errors->has('style') ? ' border-danger': ''}}" id="style" name="style" value="{{ old('style', $tag->style) }}">
	<small class="form-text text-danger">{!! $errors->first('style') !!}</small>
</div>
<input class="btn btn-primary mt-4" type="submit" value="{{ $btnText }}">

resources/views/tag/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Create New Tag</div>
                    <div class="card-body">
                        <form action="{{ route('tag.store') }}" method="post">
                            {{-- @php $btnText = 'Save Tag' @endphp --}}
							@include('tag._form', ['btnText' => 'Save Tag'])
                        </form>
                        <a class="btn btn-primary float-right" href="{{ route('tag.index') }}"><i class="fas fa-arrow-circle-up"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tag/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Edit Tag</div>
                    <div class="card-body">
						<form action="{{ route('tag.update', compact('tag')) }}" method="post">
                            @csrf @method('PUT')
                            {{-- @php $btnText = 'Update Tag' @endphp --}}
                            @include('tag._form', ['btnText' => 'Update Tag'])
                        </form>
                        <a class="btn btn-primary float-right" href="{{ route('tag.index') }}"><i class="fas fa-arrow-circle-up"></i> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tag/index.blade.php
@extends('layouts.app')

@section('page_title', 'Tag List')
@section('page_description')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">All Tags</div>

                    <div class="card-body">
                        {{-- @dump($hobbies->toArray()) --}}
                        <ul class="list-group">
                            @foreach($tags as $tag)
                                <li class="list-group-item">
                                    {{-- <a href="{{ route('hobby.show', compact('tag')) }}" title="show details">{{ $tag->name }}</a> --}}
                                    {{-- {{ $tag->name }} --}}
                                    <span style="font-size: 130%;" class="mr-2 badge badge-{{ $tag->style }}">{{ $tag->name }}</span>

                                    <a href="{{ route('tag.edit', compact('tag')) }}" class="btn btn-sm btn-outline-primary ml-3"><i class="fas fa-edit"></i> Edit</a>
                                    <form class="form-inline float-right" action="{{ route('tag.destroy', compact('tag')) }}" method="post">
                                        @csrf @method('DELETE')
                                        <input class="btn btn-sm btn-outline-danger" type="submit" value="Delete">
                                    </form>
                                    <a href="/hobby/tag/{{ $tag->id  }}" class="float-right mx-2">Used {{ $tag->hobbies->count()  }} times</a>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
                <div class="mt-2">
                    <a href="{{ route('tag.create') }}" class="btn btn-success">
                        <i class="fas fa-plus-circle"></i>
                        Create new tag
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection